### PR TITLE
Migrate from THC headers into new ones

### PR DESCRIPTION
**Pull request by mikemhenry**
This _should_ be all we need to do to update this package to build. 
I'm sure I left some cruft, this comment: https://github.com/pytorch/pytorch/issues/72807#issuecomment-1039505288 was really helpful.

### CODE REVIEW

**Comment by btalb** [comment]
Does this roughly correspond to https://github.com/conda-forge/fcos-feedstock/blob/main/recipe/patches/migrate_from_THC_to_ATen_and_c10.patch @mikemhenry ?

Having trouble testing this locally with just the Pip install due to pip installing a pytorch built with CUDA 10.2 when building the sdist, and CUDA 11+ being all that's available on my distro (all non-issues in Conda land).

Rather than figure them out here, I'll just merge and bump version number.

**Comment by mikemhenry** [comment]
Yes, I actually used this PR to make that patch, so it should be the same! 

And yah I feel your pain, the matrix of pytorch + cuda + the actual thing you want to install = pain.
That's why I'm trying to get as much stuff on conda as I can since it handles that okay, but it is much more of a pain than building a wheel and uploading that to pypi. If this PR breaks things, please feel free to tag me in any issues that users raise. I think a version bump should be safe (and then we can delete the patch in the conda-forge repo) since if it breaks stuff people can just use the older version.

**Comment by btalb** [comment]
Yep. I had this in a state where it was pip installable, but naturally the pytorch / CUDA / OS balance seems to go out the window over time.

I've bumped the version number and merged in.

Can you take care of updating the patches on conda-forge now @mikemhenry ?

Thanks again for your contributions here!

**Comment by mikemhenry** [comment]
@btalb will do!

**Comment by mikemhenry** [comment]
@btalb can you make a new pypi release so the conda-forge bot can pick up the version bump automatically? I'll still make the edits to remove the unneeded patches now.

**Comment by btalb** [comment]
Done. Sorry, forgot that step!

**Pull request merged**
